### ISSUE TITLE
pkg_resource test transparently using pkgutil ?

### ISSUE THREAD

**Issue by asmodehn** [jonparrott/namespace-pkg-tests#2]
Wouldn't this : https://github.com/jonparrott/namespace-pkg-tests/blob/master/pkg_resources_example_pkg_a/example_pkg/__init__.py#L4
mean that the package might use pkgutil while we won't be aware of it ?

Why not removing that exception handler and just let it except if pkg_resources except ?

**Comment by jonparrott** [comment]
@asmodehn yeah you're totally right, I meant to remove this. Will do soon. :)

**Comment by jonparrott** [comment]
Fixed.
